name: Build and Push Runner Image
on:
  push:
    paths:
      - "images/**"
  workflow_dispatch:
jobs:
  build:
    name: Build and Push Docker Image
    runs-on: [build]
    permissions:
      contents: read
      id-token: write
      deployments: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}/runner-deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_SECRET }}

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} images

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
